### ISSUE TITLE
Issue while loading

### ISSUE THREAD

**Issue by Garon147** [yumimobi/YumiMediationSDK-Unity#110]
Hello.
I have implemented sdk as it described in docs. After building on a device ads doesn't show. Here is the log:
[Yumi] [E] try again in 1800.000000 seconds

What does it mean? Thanks for the answers.

**Comment by JiaDingYi** [comment]
Hi, @Garon147 , thank you to use Yumi SDK.
If you see this log,  you have integrated it right.
But you may use a wrong placementID.
So send me the placementID you use, or send me a mail address.

**Comment by JiaDingYi** [comment]
Hi, @Garon147 .
if you have any questions, please let us know.
Now I should close this issue.
